# Generated by Django 6.0.4 on 2026-05-12 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('category', models.CharField(choices=[('Accompagnement', 'Accompagnement'), ('Partenariat', 'Partenariat'), ('Formation', 'Formation'), ('Événement', 'Événement'), ('Communauté', 'Communauté')], default='Accompagnement', max_length=50, verbose_name='Catégorie')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('images', models.JSONField(blank=True, default=list, help_text="Liste d'objets {name, data} ou de chemins d'images.", verbose_name='Images')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_created', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_modified', to=settings.AUTH_USER_MODEL, verbose_name='Dernier modificateur')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('publish', 'Publication'), ('unpublish', 'Dépublication')], max_length=20, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='blog.article', verbose_name='Article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Action d'audit",
                'verbose_name_plural': "Historique d'activité",
                'ordering': ['-created_at'],
            },
        ),
    ]
