# Generated by Django 6.0.4 on 2026-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('category', models.CharField(choices=[('activites', 'Activités'), ('formations', 'Formations'), ('infrastructures', 'Infrastructures')], default='activites', max_length=50, verbose_name='Catégorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Image de la galerie',
                'verbose_name_plural': 'Galerie photo',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
